---
# Setup a server for what I usually need
# ansible-playbook -i "<host>," -u root dotfiles/ansible/setup.yml
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes # next two lines install python2 on machiens where it is 3 by default
  pre_tasks:
    - name: Install Python 2
      raw: apt-get -y install python

  tasks: 
    - name: Add Docker GPG Key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      apt_repository: 
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable
      register: dockerppa

    - name: Add Neovim Repository
      apt_repository: 
        repo: ppa:neovim-ppa/stable
      register: neovimppa

    # postfix is an smtp server, right now I am only doing this so I can see mail from
    # cronjobs on the local machine
    - name: Set postfix option hostname # so that apt doesn't need any prompt 
      debconf: 
        name: postfix
        question: postfix/main_mailer_type
        value: Local Only
        vtype: string

    - name: Set postfix option hostname # so that apt doesn't need any prompt
      debconf: 
        name: postfix
        question: postfix/mailname
        value: "{{ ansible_fqdn }}"
        vtype: string

    - name: Add yarn repo
      shell: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

    - name: Install the latest go
      shell: |
        wget -O go https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz
        tar -C /usr/local -xzf go
        rm go

    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Install docker
      apt:
        name: docker-ce

    - name: Install postfix # mail client for receiving local mail
      apt:
        name: postfix

    - name: Install s-nail # client for checking mail
      apt: 
        name: s-nail

    - name: Install neovim
      apt:
        name: neovim

    - name: Install Ca-Certificated
      apt:
        name: ca-certificates

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https

    - name: Install software properties common
      apt:
        name: software-properties-common

    - name: Install docker-compose
      apt:
        name: docker-compose

    - name: Install git
      apt:
        name: git

    - name:  Install Ansible
      apt: 
        name: ansible

    - name: Install python3-pip
      apt:
        name: python3-pip

    - name: Install yarn
      apt: 
        name: yarn

    - name: Install htop
      apt:
        name: htop

    - name: Create User
      user: 
        name: jeff
        groups: sudo,docker
        password: gTb2G10SJYcbg
        shell: /bin/bash

    - name: Create user ssh folder
      file: 
        path: /home/jeff/.ssh
        state: directory
        owner: jeff
        group: jeff
        mode: 0700

    - name: Upload SSH key
      copy: 
        src: ~/.ssh/id_rsa.pub
        dest: /home/jeff/.ssh/authorized_keys
        owner: jeff
        group: jeff
        mode: 0700

    - name: Clone dotfiles, setup Go, setup NeoVim, setup Git
      become: yes
      become_user: jeff
      args: 
        executable: /bin/bash
      shell: |
        cd ~
        mkdir ~/.Trash
        mkdir -p ./bin ./go/bin ./go/src ./go/pkg
        mkdir -p ./.config/nvim/plugged ./.config/nvim/autoload ./.config/nvim/tmp 
        curl -fLo ./.config/nvim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        
        # cloning dotfiles from git repository
        git clone https://github.com/deltaskelta/dotfiles.git 
        
        # link the file so nvim can find the config when it starts
        ln -s /home/jeff/dotfiles/init.vim /home/jeff/.config/nvim/init.vim 
        ln -s /home/jeff/dotfiles/.bash_profile /home/jeff/.bash_profile 

        source /home/jeff/.bash_profile

        go get github.com/justjanne/powerline-go

        powerline-go --help

        nvim --headless +PlugInstall +qall
        nvim --headless +UpdateRemotePlugins +qall

        git config --global user.email 'jrwillette88@gmail.com'
        git config --global user.name 'deltaskelta'


    - name: Setup the SSH behavior
      shell: |
        sed -i -e '/Port 22/s/^.*$/Port 31988/' /etc/ssh/sshd_config
        sed -i -e '/PermitRootLogin yes/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
        sed -i -e '/PasswordAuthentication yes/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
        sed -i -e '$aAllowUsers jeff' /etc/ssh/sshd_config

    - name: Reboot
      command: shutdown -r 1
      ignore_errors: true
